easy_admin:
    # general parameters
    design:
        brand_color: '#e89d43'
        #form_theme: '@EasyAdmin/form/bootstrap_4.html.twig'
        # this is the default form theme used by backends
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    list:
        max_results: 10
    site_name: 'Administration BookLib'
    show:
        max_results: 10
    # List the entity class name you want to manage
    entities:
        Author:
            class: App\Entity\Author
            label: 'Auteur'
            help: ''
            list:
                title: 'Liste des auteurs'
            show:
                title: 'Auteur (#%%entity_id%%)'
            form:
                title: 'Ajouter un auteur'
            new:
            edit:
                title: 'Modifier un auteur'
        Book:
            class: App\Entity\Book
            image_base_path: '%app.path.uploads_dir%'
            label: 'Livre'
            list:
                actions:
                    - { name: 'new', icon: 'plus', label: 'Nouveau', title: 'Créer' }
                    - { name: 'show', icon: 'eye', label: false, title: 'Voir' }
                    - { name: 'edit', icon: 'pencil', label: false, title: 'Modifier' }
                    - { name: 'delete', icon: 'trash', label: false, title: 'Supprimer' }
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'reference', label: 'Référence' }
                    - { property: 'author.fullname', label: 'Auteur' }
                    - { property: 'createdAt', label: 'Date création' }
                    - { property: 'updatedAt', label: 'Date modif.' }
                    - { property: 'image', type: 'image', label: 'Couverture' }
                title: 'Livres'
            show:
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'reference', label: 'Référence' }
                    - { property: 'synopsis', label: 'Synopsis' }
                    - { property: 'createdAt', label: 'Date création'}
                    - { property: 'updatedAt', label: 'Date modif.'}
                    - { property: 'author.fullname', label: 'Auteur' }
                    - { property: 'image', type: 'image', label: 'Couverture' }
                    - { property: 'category', type_options: { expanded: true, multiple: true } }
                title: 'Livre (#%%entity_id%%)'
            form:
                fields:
                    - { type: 'group', columns: 5, icon: 'book', label: 'Informations de base' }
                    - { property: 'title', label: 'Titre' }
                    - { property: 'reference', label: 'Référence' }
                    - { property: 'slug', label: 'Slug' }
                    - { property: 'synopsis', label: 'Synopsis' }
                    - { type: 'group', label: 'Informations complémentaires' }
                    - { property: 'author', label: 'Auteur' }
                    - { property: 'category', type_options: { expanded: true, multiple: true } }
                    - { type: 'group', columns: 6 , icon: 'image', label: 'Couverture' }
                    - { property: 'imageFile', type: 'vich_image', label: 'Couverture' }
                title: 'Créer ou modifier un livre'
        Borrow:
            class: App\Entity\Borrow
            label: 'Emprunts'
        Box:
            class: App\Entity\Box
            label: 'Boîtes'
        Category:
            class: App\Entity\Category
            label: 'Genres'
        User:
            class: App\Entity\User
            label: 'Utilisateurs'
